import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) { // children 인자는 ReactNode 타입이고 읽기 전용(Readonly) 속성
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
